<div id="HELP-PAGE">
  <div class="header">
    <div class="btn-back">
      <img src="/assets/images/btn-back.png" width="75" height="75" />
    </div>
    <div class="page-title">Bitcoin ATM Help</div>
  </div>

  <div class="main-box">
    <!-- Question and answer HTML is dynamically generated at runtime.
      -- Each QA HTML entry will follow this structure:
      --      <div class="qa-box">
      --        <div class="question">Question Text</div>
      --        <div class="answer">Answer Text</div>
      --      </div>
      -->
  </div>
</div>
