<div id="START-PAGE">
  <div class="options-box">
    <img id="btn-help" src="assets/images/help-icon.png" width="75" height="75" />
    <img id="btn-lang" src="assets/images/lang-icon.png" width="75" height="75" />
  </div>
  <img class="bitcoin-logo buy-bitcoin" src="/assets/images/bitcoin.png" width="300" height="300">
  <div class="bitcoin-atm buy-bitcoin">Bitcoin ATM</div>
  <div class="btn-large-success buy-bitcoin" id="btn-buy-bitcoin">Touch to start</div>
</div>
